### ISSUE TITLE
Does twitter use Scala in a functional way?

### ISSUE THREAD

**Issue by elamje** [elamje/FunctionalProgrammingCompanyList#1]
I need confirmation from others that Scala is being used functionally at twitter in a significant way.

**Comment by hderms** [comment]
most of the open source Scala stuff I've seen from Twitter is not purely-functional Scala-as-Haskell style but it's not purely OOP. I don't have any insider knowledge, however.

Take a look around https://github.com/twitter/finagle but then you also have stuff like: https://github.com/twitter/algebird
