### ISSUE TITLE
Misleading repo name

### ISSUE THREAD

**Issue by amitnovick** [elamje/FunctionalProgrammingCompanyList#3]
It seems that this repo is an attempt to aggregate knowledge about usage of languages which have facilities which promote functional-style programming.

Sounds reasonable to me.

However, to call this `FP-over-OOP` suggests that Object-orientation features cannot co-exist with Functional-style features in one language, which I believe is patently false.

Perhaps the meaning that the person choosing the name for the repo when they were thinking about `OOP` being done in the traditional class-based style.

To illustrate how OOP and FP do not stand in contrast to each other, I suggest reading Alan Kay's answer to a question posted on this [Quora link](https://www.quora.com/Why-is-functional-programming-seen-as-the-opposite-of-OOP-rather-than-an-addition-to-it/answer/Alan-Kay-11) during 2018.

Languages that show coexistence of OOP features with FP features:
- [Clojure: Multimethods and Hierarchies](https://clojure.org/reference/multimethods)
- [JavaScript: Inheritance and the prototype chain](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)
- Python : Lambda functions, `map`, `reduce`, `filter` operations

It seems to me that the name should either:
- focus on FP alone
- or focus on specific languages that promote FP-style that you _prefer_

**Comment by elamje** [comment]
Thanks for your feedback, I will rename it to something clearer!
