### ISSUE TITLE
Add Nubank to list for Clojure and Scala

### ISSUE THREAD

**Issue by akle** [elamje/FunctionalProgrammingCompanyList#5]
Nubank

Most core backend services are in Clojure.
Scala is used extensively in our data infrastructure.

Clojure Repos
https://github.com/nubank?utf8=%E2%9C%93&q=&type=public&language=clojure

Clojure Videos
How we test at Nubank - Clojure Days
https://www.youtube.com/watch?v=X_PXoiOIdMs

Exploring four hidden superpowers of Datomic - Clojure Conf
https://www.youtube.com/watch?v=7lm3K8zVOdY

Scala Repos
https://github.com/nubank?utf8=%E2%9C%93&q=&type=public&language=scala

Scala Videos

**Comment by elamje** [comment]
👏 This is awesome! Happy to see a unicorn using some great FP! Thanks for your input.
