### ISSUE TITLE
Add WorksHub to Clojure list

### ISSUE THREAD

**Issue by nathell** [elamje/FunctionalProgrammingCompanyList#7]
**Please describe why this language or company has merit to be on the list.**
[WorksHub](https://www.works-hub.com) provides a platform for functional job seekers, called [Functional Works](https://functional.works-hub.com). The platform is itself made in Clojure/ClojureScript.

**Company: Add any proof of functional language used at company. Request others to confirm in comments.**
See https://github.com/WorksHub

(Disclosure: I work for WorksHub)

**Comment by elamje** [comment]
Nice, thanks man. You're website it really nice. I will put a link to it in a special spot.
